/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PublicSiteSlugRouteImport } from './routes/public.$siteSlug'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as PublicSiteSlugIndexRouteImport } from './routes/public.$siteSlug.index'
import { Route as PublicSiteSlugSitemapDotxmlRouteImport } from './routes/public.$siteSlug.sitemap[.]xml'
import { Route as PublicSiteSlugRobotsDottxtRouteImport } from './routes/public.$siteSlug.robots[.]txt'
import { Route as PublicSiteSlugSplatRouteImport } from './routes/public.$siteSlug.$'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'
import { Route as AppSitesSiteIdIndexRouteImport } from './routes/app.sites.$siteId.index'
import { Route as AppSitesSiteIdPreviewRouteImport } from './routes/app.sites.$siteId.preview'
import { Route as AppSitesSiteIdAnalyticsRouteImport } from './routes/app.sites.$siteId.analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicSiteSlugRoute = PublicSiteSlugRouteImport.update({
  id: '/public/$siteSlug',
  path: '/public/$siteSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSiteSlugIndexRoute = PublicSiteSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSiteSlugRoute,
} as any)
const PublicSiteSlugSitemapDotxmlRoute =
  PublicSiteSlugSitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => PublicSiteSlugRoute,
  } as any)
const PublicSiteSlugRobotsDottxtRoute =
  PublicSiteSlugRobotsDottxtRouteImport.update({
    id: '/robots.txt',
    path: '/robots.txt',
    getParentRoute: () => PublicSiteSlugRoute,
  } as any)
const PublicSiteSlugSplatRoute = PublicSiteSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicSiteSlugRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesSiteIdIndexRoute = AppSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)
const AppSitesSiteIdPreviewRoute = AppSitesSiteIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)
const AppSitesSiteIdAnalyticsRoute = AppSitesSiteIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/public/$siteSlug': typeof PublicSiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRouteWithChildren
  '/public/$siteSlug/$': typeof PublicSiteSlugSplatRoute
  '/public/$siteSlug/robots.txt': typeof PublicSiteSlugRobotsDottxtRoute
  '/public/$siteSlug/sitemap.xml': typeof PublicSiteSlugSitemapDotxmlRoute
  '/public/$siteSlug/': typeof PublicSiteSlugIndexRoute
  '/app/sites/$siteId/analytics': typeof AppSitesSiteIdAnalyticsRoute
  '/app/sites/$siteId/preview': typeof AppSitesSiteIdPreviewRoute
  '/app/sites/$siteId/': typeof AppSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/app': typeof AppIndexRoute
  '/public/$siteSlug/$': typeof PublicSiteSlugSplatRoute
  '/public/$siteSlug/robots.txt': typeof PublicSiteSlugRobotsDottxtRoute
  '/public/$siteSlug/sitemap.xml': typeof PublicSiteSlugSitemapDotxmlRoute
  '/public/$siteSlug': typeof PublicSiteSlugIndexRoute
  '/app/sites/$siteId/analytics': typeof AppSitesSiteIdAnalyticsRoute
  '/app/sites/$siteId/preview': typeof AppSitesSiteIdPreviewRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/public/$siteSlug': typeof PublicSiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRouteWithChildren
  '/public/$siteSlug/$': typeof PublicSiteSlugSplatRoute
  '/public/$siteSlug/robots.txt': typeof PublicSiteSlugRobotsDottxtRoute
  '/public/$siteSlug/sitemap.xml': typeof PublicSiteSlugSitemapDotxmlRoute
  '/public/$siteSlug/': typeof PublicSiteSlugIndexRoute
  '/app/sites/$siteId/analytics': typeof AppSitesSiteIdAnalyticsRoute
  '/app/sites/$siteId/preview': typeof AppSitesSiteIdPreviewRoute
  '/app/sites/$siteId/': typeof AppSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/login'
    | '/restore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/preview/$token'
    | '/public/$siteSlug'
    | '/app/'
    | '/app/sites/$siteId'
    | '/public/$siteSlug/$'
    | '/public/$siteSlug/robots.txt'
    | '/public/$siteSlug/sitemap.xml'
    | '/public/$siteSlug/'
    | '/app/sites/$siteId/analytics'
    | '/app/sites/$siteId/preview'
    | '/app/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/restore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/preview/$token'
    | '/app'
    | '/public/$siteSlug/$'
    | '/public/$siteSlug/robots.txt'
    | '/public/$siteSlug/sitemap.xml'
    | '/public/$siteSlug'
    | '/app/sites/$siteId/analytics'
    | '/app/sites/$siteId/preview'
    | '/app/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/login'
    | '/restore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/preview/$token'
    | '/public/$siteSlug'
    | '/app/'
    | '/app/sites/$siteId'
    | '/public/$siteSlug/$'
    | '/public/$siteSlug/robots.txt'
    | '/public/$siteSlug/sitemap.xml'
    | '/public/$siteSlug/'
    | '/app/sites/$siteId/analytics'
    | '/app/sites/$siteId/preview'
    | '/app/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RestoreRoute: typeof RestoreRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
  PublicSiteSlugRoute: typeof PublicSiteSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/$siteSlug': {
      id: '/public/$siteSlug'
      path: '/public/$siteSlug'
      fullPath: '/public/$siteSlug'
      preLoaderRoute: typeof PublicSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$siteSlug/': {
      id: '/public/$siteSlug/'
      path: '/'
      fullPath: '/public/$siteSlug/'
      preLoaderRoute: typeof PublicSiteSlugIndexRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/public/$siteSlug/sitemap.xml': {
      id: '/public/$siteSlug/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/public/$siteSlug/sitemap.xml'
      preLoaderRoute: typeof PublicSiteSlugSitemapDotxmlRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/public/$siteSlug/robots.txt': {
      id: '/public/$siteSlug/robots.txt'
      path: '/robots.txt'
      fullPath: '/public/$siteSlug/robots.txt'
      preLoaderRoute: typeof PublicSiteSlugRobotsDottxtRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/public/$siteSlug/$': {
      id: '/public/$siteSlug/$'
      path: '/$'
      fullPath: '/public/$siteSlug/$'
      preLoaderRoute: typeof PublicSiteSlugSplatRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$siteId/': {
      id: '/app/sites/$siteId/'
      path: '/'
      fullPath: '/app/sites/$siteId/'
      preLoaderRoute: typeof AppSitesSiteIdIndexRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
    '/app/sites/$siteId/preview': {
      id: '/app/sites/$siteId/preview'
      path: '/preview'
      fullPath: '/app/sites/$siteId/preview'
      preLoaderRoute: typeof AppSitesSiteIdPreviewRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
    '/app/sites/$siteId/analytics': {
      id: '/app/sites/$siteId/analytics'
      path: '/analytics'
      fullPath: '/app/sites/$siteId/analytics'
      preLoaderRoute: typeof AppSitesSiteIdAnalyticsRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
  }
}

interface AppSitesSiteIdRouteChildren {
  AppSitesSiteIdAnalyticsRoute: typeof AppSitesSiteIdAnalyticsRoute
  AppSitesSiteIdPreviewRoute: typeof AppSitesSiteIdPreviewRoute
  AppSitesSiteIdIndexRoute: typeof AppSitesSiteIdIndexRoute
}

const AppSitesSiteIdRouteChildren: AppSitesSiteIdRouteChildren = {
  AppSitesSiteIdAnalyticsRoute: AppSitesSiteIdAnalyticsRoute,
  AppSitesSiteIdPreviewRoute: AppSitesSiteIdPreviewRoute,
  AppSitesSiteIdIndexRoute: AppSitesSiteIdIndexRoute,
}

const AppSitesSiteIdRouteWithChildren = AppSitesSiteIdRoute._addFileChildren(
  AppSitesSiteIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSitesSiteIdRoute: AppSitesSiteIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicSiteSlugRouteChildren {
  PublicSiteSlugSplatRoute: typeof PublicSiteSlugSplatRoute
  PublicSiteSlugRobotsDottxtRoute: typeof PublicSiteSlugRobotsDottxtRoute
  PublicSiteSlugSitemapDotxmlRoute: typeof PublicSiteSlugSitemapDotxmlRoute
  PublicSiteSlugIndexRoute: typeof PublicSiteSlugIndexRoute
}

const PublicSiteSlugRouteChildren: PublicSiteSlugRouteChildren = {
  PublicSiteSlugSplatRoute: PublicSiteSlugSplatRoute,
  PublicSiteSlugRobotsDottxtRoute: PublicSiteSlugRobotsDottxtRoute,
  PublicSiteSlugSitemapDotxmlRoute: PublicSiteSlugSitemapDotxmlRoute,
  PublicSiteSlugIndexRoute: PublicSiteSlugIndexRoute,
}

const PublicSiteSlugRouteWithChildren = PublicSiteSlugRoute._addFileChildren(
  PublicSiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RestoreRoute: RestoreRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PreviewTokenRoute: PreviewTokenRoute,
  PublicSiteSlugRoute: PublicSiteSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
