/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PublicSiteSlugRouteImport } from './routes/public.$siteSlug'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as PublicSiteSlugIndexRouteImport } from './routes/public.$siteSlug.index'
import { Route as AppBillingIndexRouteImport } from './routes/app.billing.index'
import { Route as PublicSiteSlugSitemapDotxmlRouteImport } from './routes/public.$siteSlug.sitemap[.]xml'
import { Route as PublicSiteSlugRobotsDottxtRouteImport } from './routes/public.$siteSlug.robots[.]txt'
import { Route as PublicSiteSlugSplatRouteImport } from './routes/public.$siteSlug.$'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'
import { Route as AppBillingSuccessRouteImport } from './routes/app.billing.success'
import { Route as AppBillingCancelRouteImport } from './routes/app.billing.cancel'
import { Route as AppAdminOnceOverRouteImport } from './routes/app.admin.once-over'
import { Route as AppSitesSiteIdIndexRouteImport } from './routes/app.sites.$siteId.index'
import { Route as AppSitesSiteIdPreviewRouteImport } from './routes/app.sites.$siteId.preview'
import { Route as AppSitesSiteIdCollectionsRouteImport } from './routes/app.sites.$siteId.collections'
import { Route as AppSitesSiteIdAnalyticsRouteImport } from './routes/app.sites.$siteId.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicSiteSlugRoute = PublicSiteSlugRouteImport.update({
  id: '/public/$siteSlug',
  path: '/public/$siteSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const PublicSiteSlugIndexRoute = PublicSiteSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSiteSlugRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const PublicSiteSlugSitemapDotxmlRoute =
  PublicSiteSlugSitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => PublicSiteSlugRoute,
  } as any)
const PublicSiteSlugRobotsDottxtRoute =
  PublicSiteSlugRobotsDottxtRouteImport.update({
    id: '/robots.txt',
    path: '/robots.txt',
    getParentRoute: () => PublicSiteSlugRoute,
  } as any)
const PublicSiteSlugSplatRoute = PublicSiteSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicSiteSlugRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingSuccessRoute = AppBillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingCancelRoute = AppBillingCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppAdminOnceOverRoute = AppAdminOnceOverRouteImport.update({
  id: '/admin/once-over',
  path: '/admin/once-over',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesSiteIdIndexRoute = AppSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)
const AppSitesSiteIdPreviewRoute = AppSitesSiteIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)
const AppSitesSiteIdCollectionsRoute =
  AppSitesSiteIdCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AppSitesSiteIdRoute,
  } as any)
const AppSitesSiteIdAnalyticsRoute = AppSitesSiteIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppSitesSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/restore': typeof RestoreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/preview/$token': typeof PreviewTokenRoute
  '/public/$siteSlug': typeof PublicSiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/once-over': typeof AppAdminOnceOverRoute
  '/app/billing/cancel': typeof AppBillingCancelRoute
  '/app/billing/success': typeof AppBillingSuccessRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRouteWithChildren
  '/public/$siteSlug/$': typeof PublicSiteSlugSplatRoute
  '/public/$siteSlug/robots.txt': typeof PublicSiteSlugRobotsDottxtRoute
  '/public/$siteSlug/sitemap.xml': typeof PublicSiteSlugSitemapDotxmlRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/public/$siteSlug/': typeof PublicSiteSlugIndexRoute
  '/app/sites/$siteId/analytics': typeof AppSitesSiteIdAnalyticsRoute
  '/app/sites/$siteId/collections': typeof AppSitesSiteIdCollectionsRoute
  '/app/sites/$siteId/preview': typeof AppSitesSiteIdPreviewRoute
  '/app/sites/$siteId/': typeof AppSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/restore': typeof RestoreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/app': typeof AppIndexRoute
  '/app/admin/once-over': typeof AppAdminOnceOverRoute
  '/app/billing/cancel': typeof AppBillingCancelRoute
  '/app/billing/success': typeof AppBillingSuccessRoute
  '/public/$siteSlug/$': typeof PublicSiteSlugSplatRoute
  '/public/$siteSlug/robots.txt': typeof PublicSiteSlugRobotsDottxtRoute
  '/public/$siteSlug/sitemap.xml': typeof PublicSiteSlugSitemapDotxmlRoute
  '/app/billing': typeof AppBillingIndexRoute
  '/public/$siteSlug': typeof PublicSiteSlugIndexRoute
  '/app/sites/$siteId/analytics': typeof AppSitesSiteIdAnalyticsRoute
  '/app/sites/$siteId/collections': typeof AppSitesSiteIdCollectionsRoute
  '/app/sites/$siteId/preview': typeof AppSitesSiteIdPreviewRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/restore': typeof RestoreRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/preview/$token': typeof PreviewTokenRoute
  '/public/$siteSlug': typeof PublicSiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/once-over': typeof AppAdminOnceOverRoute
  '/app/billing/cancel': typeof AppBillingCancelRoute
  '/app/billing/success': typeof AppBillingSuccessRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRouteWithChildren
  '/public/$siteSlug/$': typeof PublicSiteSlugSplatRoute
  '/public/$siteSlug/robots.txt': typeof PublicSiteSlugRobotsDottxtRoute
  '/public/$siteSlug/sitemap.xml': typeof PublicSiteSlugSitemapDotxmlRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/public/$siteSlug/': typeof PublicSiteSlugIndexRoute
  '/app/sites/$siteId/analytics': typeof AppSitesSiteIdAnalyticsRoute
  '/app/sites/$siteId/collections': typeof AppSitesSiteIdCollectionsRoute
  '/app/sites/$siteId/preview': typeof AppSitesSiteIdPreviewRoute
  '/app/sites/$siteId/': typeof AppSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/login'
    | '/privacy'
    | '/restore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/app/billing'
    | '/preview/$token'
    | '/public/$siteSlug'
    | '/app/'
    | '/app/admin/once-over'
    | '/app/billing/cancel'
    | '/app/billing/success'
    | '/app/sites/$siteId'
    | '/public/$siteSlug/$'
    | '/public/$siteSlug/robots.txt'
    | '/public/$siteSlug/sitemap.xml'
    | '/app/billing/'
    | '/public/$siteSlug/'
    | '/app/sites/$siteId/analytics'
    | '/app/sites/$siteId/collections'
    | '/app/sites/$siteId/preview'
    | '/app/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/privacy'
    | '/restore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/preview/$token'
    | '/app'
    | '/app/admin/once-over'
    | '/app/billing/cancel'
    | '/app/billing/success'
    | '/public/$siteSlug/$'
    | '/public/$siteSlug/robots.txt'
    | '/public/$siteSlug/sitemap.xml'
    | '/app/billing'
    | '/public/$siteSlug'
    | '/app/sites/$siteId/analytics'
    | '/app/sites/$siteId/collections'
    | '/app/sites/$siteId/preview'
    | '/app/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/login'
    | '/privacy'
    | '/restore'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/app/billing'
    | '/preview/$token'
    | '/public/$siteSlug'
    | '/app/'
    | '/app/admin/once-over'
    | '/app/billing/cancel'
    | '/app/billing/success'
    | '/app/sites/$siteId'
    | '/public/$siteSlug/$'
    | '/public/$siteSlug/robots.txt'
    | '/public/$siteSlug/sitemap.xml'
    | '/app/billing/'
    | '/public/$siteSlug/'
    | '/app/sites/$siteId/analytics'
    | '/app/sites/$siteId/collections'
    | '/app/sites/$siteId/preview'
    | '/app/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RestoreRoute: typeof RestoreRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
  PublicSiteSlugRoute: typeof PublicSiteSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/$siteSlug': {
      id: '/public/$siteSlug'
      path: '/public/$siteSlug'
      fullPath: '/public/$siteSlug'
      preLoaderRoute: typeof PublicSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/$siteSlug/': {
      id: '/public/$siteSlug/'
      path: '/'
      fullPath: '/public/$siteSlug/'
      preLoaderRoute: typeof PublicSiteSlugIndexRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/app/billing/': {
      id: '/app/billing/'
      path: '/'
      fullPath: '/app/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/public/$siteSlug/sitemap.xml': {
      id: '/public/$siteSlug/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/public/$siteSlug/sitemap.xml'
      preLoaderRoute: typeof PublicSiteSlugSitemapDotxmlRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/public/$siteSlug/robots.txt': {
      id: '/public/$siteSlug/robots.txt'
      path: '/robots.txt'
      fullPath: '/public/$siteSlug/robots.txt'
      preLoaderRoute: typeof PublicSiteSlugRobotsDottxtRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/public/$siteSlug/$': {
      id: '/public/$siteSlug/$'
      path: '/$'
      fullPath: '/public/$siteSlug/$'
      preLoaderRoute: typeof PublicSiteSlugSplatRouteImport
      parentRoute: typeof PublicSiteSlugRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing/success': {
      id: '/app/billing/success'
      path: '/success'
      fullPath: '/app/billing/success'
      preLoaderRoute: typeof AppBillingSuccessRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/app/billing/cancel': {
      id: '/app/billing/cancel'
      path: '/cancel'
      fullPath: '/app/billing/cancel'
      preLoaderRoute: typeof AppBillingCancelRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/app/admin/once-over': {
      id: '/app/admin/once-over'
      path: '/admin/once-over'
      fullPath: '/app/admin/once-over'
      preLoaderRoute: typeof AppAdminOnceOverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$siteId/': {
      id: '/app/sites/$siteId/'
      path: '/'
      fullPath: '/app/sites/$siteId/'
      preLoaderRoute: typeof AppSitesSiteIdIndexRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
    '/app/sites/$siteId/preview': {
      id: '/app/sites/$siteId/preview'
      path: '/preview'
      fullPath: '/app/sites/$siteId/preview'
      preLoaderRoute: typeof AppSitesSiteIdPreviewRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
    '/app/sites/$siteId/collections': {
      id: '/app/sites/$siteId/collections'
      path: '/collections'
      fullPath: '/app/sites/$siteId/collections'
      preLoaderRoute: typeof AppSitesSiteIdCollectionsRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
    '/app/sites/$siteId/analytics': {
      id: '/app/sites/$siteId/analytics'
      path: '/analytics'
      fullPath: '/app/sites/$siteId/analytics'
      preLoaderRoute: typeof AppSitesSiteIdAnalyticsRouteImport
      parentRoute: typeof AppSitesSiteIdRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingCancelRoute: typeof AppBillingCancelRoute
  AppBillingSuccessRoute: typeof AppBillingSuccessRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingCancelRoute: AppBillingCancelRoute,
  AppBillingSuccessRoute: AppBillingSuccessRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppSitesSiteIdRouteChildren {
  AppSitesSiteIdAnalyticsRoute: typeof AppSitesSiteIdAnalyticsRoute
  AppSitesSiteIdCollectionsRoute: typeof AppSitesSiteIdCollectionsRoute
  AppSitesSiteIdPreviewRoute: typeof AppSitesSiteIdPreviewRoute
  AppSitesSiteIdIndexRoute: typeof AppSitesSiteIdIndexRoute
}

const AppSitesSiteIdRouteChildren: AppSitesSiteIdRouteChildren = {
  AppSitesSiteIdAnalyticsRoute: AppSitesSiteIdAnalyticsRoute,
  AppSitesSiteIdCollectionsRoute: AppSitesSiteIdCollectionsRoute,
  AppSitesSiteIdPreviewRoute: AppSitesSiteIdPreviewRoute,
  AppSitesSiteIdIndexRoute: AppSitesSiteIdIndexRoute,
}

const AppSitesSiteIdRouteWithChildren = AppSitesSiteIdRoute._addFileChildren(
  AppSitesSiteIdRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminOnceOverRoute: typeof AppAdminOnceOverRoute
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminOnceOverRoute: AppAdminOnceOverRoute,
  AppSitesSiteIdRoute: AppSitesSiteIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicSiteSlugRouteChildren {
  PublicSiteSlugSplatRoute: typeof PublicSiteSlugSplatRoute
  PublicSiteSlugRobotsDottxtRoute: typeof PublicSiteSlugRobotsDottxtRoute
  PublicSiteSlugSitemapDotxmlRoute: typeof PublicSiteSlugSitemapDotxmlRoute
  PublicSiteSlugIndexRoute: typeof PublicSiteSlugIndexRoute
}

const PublicSiteSlugRouteChildren: PublicSiteSlugRouteChildren = {
  PublicSiteSlugSplatRoute: PublicSiteSlugSplatRoute,
  PublicSiteSlugRobotsDottxtRoute: PublicSiteSlugRobotsDottxtRoute,
  PublicSiteSlugSitemapDotxmlRoute: PublicSiteSlugSitemapDotxmlRoute,
  PublicSiteSlugIndexRoute: PublicSiteSlugIndexRoute,
}

const PublicSiteSlugRouteWithChildren = PublicSiteSlugRoute._addFileChildren(
  PublicSiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RestoreRoute: RestoreRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  PreviewTokenRoute: PreviewTokenRoute,
  PublicSiteSlugRoute: PublicSiteSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
