package generation

// enGenCatalog is the English deterministic fallback copy. It is the source of
// truth for the copy contract: every string here has an Icelandic counterpart
// in isGenCatalog, enforced by the parity tests in localized_copy_test.go.
var enGenCatalog = genCatalog{
	Profiles: map[string]genProfileCopy{
		categoryBusiness: {
			CategoryLabel: "Small business website",
			PrimaryCTA:    "Get in touch",
			ServicesTitle: "What you can book or buy",
			ServicesIntro: "A concise overview of the main offers people should understand before they reach out.",
			FeatureItems: []genFeature{
				{Title: "Clear offer", Body: "Explain the core service in direct language without turning the homepage into a project."},
				{Title: "Friendly process", Body: "Set expectations, answer obvious questions, and make the next step feel easy."},
				{Title: "Simple contact", Body: "Point visitors toward one action that turns interest into an actual conversation."},
			},
			AboutHeading:    "A small operation with a real point of view",
			AboutBody:       "Use this section to explain how the work feels, who it is for, and why customers trust you to do it well.",
			GalleryHeading:  "Selected work",
			GalleryBody:     "Show a focused sample of recent work, finished pieces, or notable projects so visitors can picture the result.",
			ContactHeading:  "Start the conversation",
			ContactBody:     "Make it easy for a visitor to ask a question, book a time, or request a quote without hunting for the next step.",
			SiteGoal:        "Turn visitors into clear, low-friction inquiries.",
			HomeHeadline:    "%s needs a clear, confident website that gets to the point",
			HomeSubheadline: "This first draft keeps the message short, the structure clear, and the next step obvious.",
			AboutIntro:      "Small business sites work better when the visitor can understand the offer, the style, and the next step in under a minute.",
			WorkProcess:     "Use this section to replace vague promises with a short description of how the work actually happens and what a customer gets from it.",
			FooterTagline:   "A small, focused website that keeps the next step close.",
		},
		"photography": {
			CategoryLabel: "Photography studio",
			PrimaryCTA:    "Book a session",
			ServicesTitle: "Sessions and coverage",
			ServicesIntro: "Group the main shoot types together so people can quickly see what you cover and what kind of experience you offer.",
			FeatureItems: []genFeature{
				{Title: "Portrait sessions", Body: "Natural, low-pressure shoots for people who want honest photos without stiff direction."},
				{Title: "Brand imagery", Body: "A tidy set of images for websites, campaigns, launches, and day-to-day marketing."},
				{Title: "Events and occasions", Body: "Coverage that keeps the day moving while still catching the moments people actually remember."},
			},
			AboutHeading:    "A calm process makes better photographs",
			AboutBody:       "Use this space to describe your visual style, what a session feels like, and why clients leave with images that still feel like themselves.",
			GalleryHeading:  "Recent shoots",
			GalleryBody:     "Break the work into a few focused examples: portraits, events, or brand sessions that show range without overwhelming the page.",
			SiteGoal:        "Turn visitors into photography inquiries and bookings.",
			HomeHeadline:    "Natural photography for real people, places, and moments",
			HomeSubheadline: "Use this draft to introduce your style, show the work, and make booking a session feel straightforward.",
			AboutIntro:      "Lead with the kind of moments you help people keep, then describe the relaxed experience around the camera.",
			WorkProcess:     "A strong draft process usually moves from a quick inquiry to clear planning, a low-drama shoot, and a tidy handoff of the final images.",
			FooterTagline:   "Calm planning, honest images, and a straightforward path to booking.",
		},
		"florist": {
			CategoryLabel: "Florist studio",
			PrimaryCTA:    "Ask about an order",
			ServicesTitle: "Seasonal flower work",
			ServicesIntro: "Call out the formats that matter most: weddings, weekly flowers, custom orders, and one-off installations.",
			FeatureItems: []genFeature{
				{Title: "Event flowers", Body: "Design for dinners, launches, celebrations, and weddings that need warmth rather than fuss."},
				{Title: "Weekly arrangements", Body: "Recurring flowers for shops, studios, offices, or homes that want the room to feel lived in."},
				{Title: "Custom orders", Body: "Smaller commissions, gift bouquets, and specific requests handled with a clear process."},
			},
			SiteGoal:        "Turn visitors into flower orders, event inquiries, and repeat customers.",
			HomeHeadline:    "Flowers for gatherings, gifting, and the everyday table",
			HomeSubheadline: "Start with a warm overview of seasonal work, custom orders, and the events or spaces you help shape.",
			AboutIntro:      "Anchor the page in seasonality, mood, and the practical kinds of orders you actually want to receive.",
			WorkProcess:     "Keep the process readable: a short inquiry, a quick alignment on scale and mood, then a clear path to delivery or installation.",
		},
		"wellness": {
			CategoryLabel: "Wellness practice",
			PrimaryCTA:    "Book a session",
			ServicesTitle: "Sessions and support",
			ServicesIntro: "Focus on the few ways people can work with you so the path from curiosity to booking stays short.",
			FeatureItems: []genFeature{
				{Title: "Private sessions", Body: "One-to-one support tuned to a person, a goal, or a season of life."},
				{Title: "Group offerings", Body: "Classes, circles, or small-group formats that create rhythm without losing the human feel."},
				{Title: "Practical guidance", Body: "A grounded explanation of what happens, who it helps, and how to know if it is a fit."},
			},
			SiteGoal:        "Turn visitors into session bookings and confident first conversations.",
			HomeHeadline:    "A steadier practice for busy bodies and loud minds",
			HomeSubheadline: "Give new visitors a calm explanation of what you offer, who it helps, and the easiest way to begin.",
			AboutIntro:      "Explain your approach plainly: what happens, how it feels, and what someone should expect after the first session.",
			WorkProcess:     "The point here is clarity: who this is for, what support looks like in practice, and how people know when to reach out.",
			FooterTagline:   "Grounded support, plain language, and a gentler first step.",
		},
		"creative": {
			CategoryLabel: "Creative studio",
			PrimaryCTA:    "Start a project",
			ServicesTitle: "Services and retainers",
			ServicesIntro: "Keep the offer structured around a few outcomes instead of a long inventory of tasks.",
			FeatureItems: []genFeature{
				{Title: "Brand systems", Body: "Identity work that gives small businesses a clearer shape, voice, and visual rhythm."},
				{Title: "Launch pages", Body: "Focused pages for offers, openings, or campaigns that need to ship without drag."},
				{Title: "Ongoing support", Body: "A flexible way to keep copy, design, and site updates moving after the first launch."},
			},
			SiteGoal:        "Turn visitors into well-qualified project inquiries.",
			HomeHeadline:    "Thoughtful design for small businesses that need to look ready",
			HomeSubheadline: "Frame the offer around outcomes, not jargon, so good-fit clients understand the value quickly.",
			AboutIntro:      "Describe the way you work with small teams so the process feels structured without sounding rigid or inflated.",
			WorkProcess:     "Good-fit projects start with scope, direction, and a clean decision-maker path, then move through concise rounds instead of endless drift.",
		},
		"craft": {
			CategoryLabel: "Craft studio",
			PrimaryCTA:    "See upcoming workshops",
			ServicesTitle: "Pieces, commissions, and workshops",
			ServicesIntro: "Explain what is available now, what can be commissioned, and how classes or workshops fit into the business.",
			FeatureItems: []genFeature{
				{Title: "Small-batch pieces", Body: "Limited runs and seasonal releases with enough context to make each piece feel tangible."},
				{Title: "Custom work", Body: "Commission pathways for customers who want something made for a space, event, or gift."},
				{Title: "Hands-on workshops", Body: "Short classes that let people learn the material, process, and rhythm behind the work."},
			},
			SiteGoal:        "Turn visitors into workshop bookings, commissions, and product interest.",
			HomeHeadline:    "Handmade work with real texture, practical beauty, and room to learn",
			HomeSubheadline: "Explain the mix of products, commissions, and workshops in one place without losing the handmade feel.",
			AboutIntro:      "Use the page to connect the finished pieces with the materials, techniques, and teaching behind them.",
			WorkProcess:     "People respond well when they can see the handwork and understand the rhythm behind it, whether that ends in a class, a commission, or a purchase.",
			FooterTagline:   "Handmade work, practical beauty, and room to learn by doing.",
		},
		"food": {
			CategoryLabel: "Local food business",
			PrimaryCTA:    "Plan a visit",
			ServicesTitle: "Menu highlights and orders",
			ServicesIntro: "Keep the story practical: what is available, when to stop by, and how to order for larger needs.",
			FeatureItems: []genFeature{
				{Title: "Daily offering", Body: "A rotating line of fresh items that keeps regulars curious and first-time visitors oriented."},
				{Title: "Pre-orders", Body: "A clear way to reserve cakes, boxes, or larger orders without forcing a long back-and-forth."},
				{Title: "Events and catering", Body: "A simple summary of what kinds of gatherings you support and how to ask about them."},
			},
			SiteGoal:        "Turn visitors into visits, pre-orders, and catering inquiries.",
			HomeHeadline:    "A local spot people want to return to",
			HomeSubheadline: "Show the atmosphere, the offering, and the practical next step before the visitor bounces for logistics.",
			AboutIntro:      "A good food site gives enough atmosphere to make a visit sound appealing without turning basic details into a scavenger hunt.",
			WorkProcess:     "Food businesses benefit from a simple explanation of what is fresh, what changes often, and how larger or special orders are handled.",
		},
	},
	Pricing: map[string][]genPricingPlan{
		"photography": {
			{
				Name:        "Portrait session",
				Price:       "From $450",
				Description: "A focused session for individuals, couples, or families who want relaxed direction and a tidy final gallery.",
				Features:    []string{"Planning call", "Edited image set", "Private gallery"},
				CTALabel:    "Ask about sessions",
			},
			{
				Name:        "Brand coverage",
				Price:       "From $900",
				Description: "A half-day or full-day package for launches, campaigns, or small-business website imagery.",
				Features:    []string{"Shot list support", "Usage-ready edits", "Delivery plan"},
				CTALabel:    "Plan your shoot",
			},
		},
		"wellness": {
			{
				Name:        "Private sessions",
				Price:       "From $120",
				Description: "One-to-one work for people who want dedicated support and a calmer starting point.",
				Features:    []string{"Individual pacing", "Practical guidance", "Follow-up notes"},
				CTALabel:    "Ask about sessions",
			},
			{
				Name:        "Small-group series",
				Price:       "From $280",
				Description: "A short series for people who want continuity, structure, and a shared rhythm.",
				Features:    []string{"Group format", "Repeat sessions", "Clear next steps"},
				CTALabel:    "Ask about dates",
			},
		},
		categoryBusiness: {
			{
				Name:        "Starter",
				Price:       "From $350",
				Description: "A smaller package for focused work where the goal and scope are already fairly clear.",
				Features:    []string{"Defined scope", "Clear timeline", "Simple handoff"},
				CTALabel:    "Ask about fit",
			},
			{
				Name:        "Signature",
				Price:       "From $900",
				Description: "A broader package for projects that need more collaboration, shaping, or coverage.",
				Features:    []string{"Collaborative planning", "More coverage", "Refined delivery"},
				CTALabel:    "Start the conversation",
			},
		},
	},
	Testimonials: map[string][]genTestimonial{
		"photography": {
			{Quote: "The whole process felt calm and clear, and the photos still looked like us instead of a version of us trying too hard.", Name: "Mira L.", Role: "Portrait client"},
			{Quote: "We got a set of images that finally made the website feel current, consistent, and ready to send people to.", Name: "Aren Studio", Role: "Brand client"},
		},
		"wellness": {
			{Quote: "The sessions felt grounded from the first minute, and I left knowing exactly what I wanted to keep practicing.", Name: "Elin S.", Role: "Private client"},
			{Quote: "Everything was explained plainly, which made it much easier to book than other places I looked at.", Name: "Johan K.", Role: "New client"},
		},
		categoryBusiness: {
			{Quote: "The whole thing felt surprisingly easy, and the result looked more polished than I expected this early in the process.", Name: "Nora P.", Role: "Client"},
			{Quote: "Clear communication, no fuss, and a final result that actually matched how we wanted the business to come across.", Name: "S. Berg", Role: "Owner"},
		},
	},
	FAQ: map[string][]genFAQ{
		"photography": {
			{Question: "How much detail should I send in the first email?", Answer: "A short note about the kind of shoot, rough timing, and what you need the images to do is enough to start."},
			{Question: "Do I need a final brief before reaching out?", Answer: "No. A rough idea is fine, and the specifics can be shaped together once the first conversation starts."},
		},
		"wellness": {
			{Question: "How do I know if this is the right fit for me?", Answer: "Use the first conversation to ask practical questions about pace, format, and what support usually looks like."},
			{Question: "What should I bring to the first session?", Answer: "A short sense of what feels difficult right now and what kind of support you hope to get is usually enough."},
		},
		categoryBusiness: {
			{Question: "What should someone include in the first inquiry?", Answer: "A little context about timing, scope, and the kind of help you need is enough to get a useful conversation started."},
			{Question: "Do you work with smaller projects as well?", Answer: "Use this answer to clarify whether there is a minimum scope, a starter package, or a referral path when something is too small."},
		},
	},
	Team: map[string][]genTeamMember{
		"creative": {
			{Name: "Creative lead", Role: "Direction and framing", Bio: "Shapes the brief, keeps the work focused, and makes sure the final result still sounds like the business.", Links: []genLink{{Label: "Start a project", Href: "/contact"}}},
			{Name: "Project partner", Role: "Planning and delivery", Bio: "Handles timing, revisions, and the practical details that keep a small project from turning into a long one.", Links: []genLink{{Label: "Ask a question", Href: "/contact"}}},
		},
		categoryBusiness: {
			{Name: "Founder", Role: "Lead point of contact", Bio: "Owns the work, keeps communication direct, and stays close to the details that shape the final experience.", Links: []genLink{{Label: "Get in touch", Href: "/contact"}}},
		},
	},
	UI: map[string]string{
		"nav.home":      "Home",
		"nav.services":  "Services",
		"nav.workshops": "Workshops",
		"nav.gallery":   "Gallery",
		"nav.about":     "About",
		"nav.contact":   "Contact",

		"home.textHeading":  "A first draft shaped around the actual work",
		"home.imageHeading": "How the work usually feels",

		"services.featuresHeading": "What this includes",
		"services.featuresIntro":   "Use these cards to outline the typical formats, deliverables, or ways someone can work with you.",
		"services.ctaHeading":      "Need a version of this tailored to your project?",
		"services.ctaBody":         "Invite people to ask about timing, scope, or fit instead of making them guess how to start.",

		"workshops.item1.title":     "Intro sessions",
		"workshops.item1.body":      "A low-pressure first step for people who want to try the format before committing to more.",
		"workshops.item2.title":     "Small-group workshops",
		"workshops.item2.body":      "Focused sessions with enough structure to teach a useful skill and enough space to keep them human.",
		"workshops.item3.title":     "Private bookings",
		"workshops.item3.body":      "Custom sessions for teams, events, or people who need a more specific format.",
		"workshops.textHeading":     "Learn it by doing it",
		"workshops.textBody":        "Describe the pace, materials, and level of guidance so people can quickly tell whether the class fits them.",
		"workshops.featuresHeading": "Ways to join",
		"workshops.featuresIntro":   "Use these cards as the starting menu for your teaching formats.",
		"workshops.ctaHeading":      "Want the next date or a private booking?",
		"workshops.ctaBody":         "Invite the conversation before you build a more complex enrollment flow.",
		"workshops.ctaLabel":        "Ask about workshops",
		"workshops.seoDescription":  "Classes, small-group sessions, and private bookings.",

		"about.imageHeading": "Why people come back",
		"about.ctaHeading":   "If the approach fits, the next step should be simple",
		"about.ctaBody":      "Use the close of this page to invite a visit, a question, or a booking without changing tone.",

		"gallery.galleryHeading": "A small set of representative highlights",
		"gallery.galleryIntro":   "These slots can hold portfolio images, event examples, or product shots without needing a larger media system yet.",
		"gallery.image1.title":   "Signature example",
		"gallery.image1.caption": "Use the first slot for the work that best captures the tone of the business.",
		"gallery.image2.title":   "Process detail",
		"gallery.image2.caption": "Add a closer view that shows texture, materials, or the way the work is made.",
		"gallery.image3.title":   "Finished outcome",
		"gallery.image3.caption": "Use the final slot to show the result in context so visitors can picture the real-world use.",
		"gallery.ctaHeading":     "Seen enough to ask about your own project?",
		"gallery.ctaBody":        "This page should end with the clearest contact action, not with a dead stop.",

		"contact.eyebrow":         "Contact",
		"contact.heroCtaLabel":    "Send an inquiry",
		"contact.textHeading":     "What to include when you reach out",
		"contact.textBody":        "A short note about timing, budget, scale, or the kind of help you need is enough to start a useful conversation.",
		"contact.formHeading":     "Send a quick inquiry",
		"contact.formIntro":       "Use the form for timing, availability, custom requests, or the first question that gets the project moving.",
		"contact.formSubmitLabel": "Send inquiry",
		"contact.field.name":      "Name",
		"contact.field.email":     "Email",
		"contact.field.phone":     "Phone",
		"contact.field.message":   "Message",
		"contact.ctaHeading":      "Prefer email first?",
		"contact.ctaBody":         "Keep a direct email path visible for people who would rather write from their own inbox.",
		"contact.ctaLabel":        "Email hello@example.com",

		"testimonials.heading":   "What clients tend to notice",
		"testimonials.intro":     "Keep the quotes short, concrete, and tied to the real experience of working together.",
		"pricing.heading":        "Packages and starting points",
		"pricing.intro":          "Use these as clear entry points so visitors can understand scale before they reach out.",
		"faq.heading":            "Questions people ask before they reach out",
		"faq.intro":              "Use this space to lower friction, set expectations, and make the next step feel straightforward.",
		"team.heading":           "People behind the work",
		"team.intro":             "A small team section works best when it explains what each person actually brings to the client experience.",
		"footer.copyrightPrefix": "Copyright 2026 ",

		"assumptions.contact":   "Contact routes use placeholder email copy until forms or real contact details are added.",
		"assumptions.gallery":   "Visual sections use placeholder image slots until asset uploads are available.",
		"assumptions.workshops": "Workshop and class information is presented as structured marketing content, not a booking system.",
	},
}
