package generation

// isGenCatalog is the Icelandic deterministic fallback copy. It is written in a
// natural small-business register (Spec 22), not translated word-for-word from
// English, and mirrors every key in enGenCatalog so an Icelandic site never
// falls back to English copy on the deterministic path.
var isGenCatalog = genCatalog{
	Profiles: map[string]genProfileCopy{
		categoryBusiness: {
			CategoryLabel: "Vefsíða fyrir lítið fyrirtæki",
			PrimaryCTA:    "Hafðu samband",
			ServicesTitle: "Það sem hægt er að bóka eða kaupa",
			ServicesIntro: "Stutt yfirlit yfir helstu þjónustuna sem gott er að þekkja áður en haft er samband.",
			FeatureItems: []genFeature{
				{Title: "Skýrt tilboð", Body: "Lýstu kjarnaþjónustunni með einföldum orðum án þess að forsíðan verði heilt verkefni."},
				{Title: "Þægilegt ferli", Body: "Settu væntingar, svaraðu augljósum spurningum og gerðu næsta skref auðvelt."},
				{Title: "Einfalt að hafa samband", Body: "Beindu gestum að einu skrefi sem breytir áhuga í raunverulegt samtal."},
			},
			AboutHeading:    "Lítið fyrirtæki með skýra sýn",
			AboutBody:       "Notaðu þennan kafla til að útskýra hvernig vinnan er, fyrir hverja hún er og af hverju fólk treystir þér fyrir henni.",
			GalleryHeading:  "Valin verk",
			GalleryBody:     "Sýndu afmarkað úrval af nýlegum verkum, fullkláruðum hlutum eða eftirtektarverðum verkefnum svo gestir sjái útkomuna fyrir sér.",
			ContactHeading:  "Byrjum samtalið",
			ContactBody:     "Gerðu gestum auðvelt að spyrja, bóka tíma eða biðja um verðtilboð án þess að leita að næsta skrefi.",
			SiteGoal:        "Breyta gestum í skýrar og einfaldar fyrirspurnir.",
			HomeHeadline:    "%s þarf skýra og einbeitta vefsíðu sem kemst beint að efninu",
			HomeSubheadline: "Þessi fyrstu drög halda skilaboðunum stuttum, byggingunni skýrri og næsta skrefi augljósu.",
			AboutIntro:      "Vefsíður lítilla fyrirtækja virka best þegar gesturinn skilur tilboðið, stílinn og næsta skref á innan við mínútu.",
			WorkProcess:     "Notaðu þennan kafla til að skipta óljósum loforðum út fyrir stutta lýsingu á því hvernig vinnan fer raunverulega fram og hvað viðskiptavinurinn fær út úr henni.",
			FooterTagline:   "Lítil og markviss vefsíða sem heldur næsta skrefi innan seilingar.",
		},
		"photography": {
			CategoryLabel: "Ljósmyndastofa",
			PrimaryCTA:    "Bókaðu myndatöku",
			ServicesTitle: "Myndatökur og verkefni",
			ServicesIntro: "Taktu saman helstu tegundir myndatöku svo fólk sjái fljótt hvað þú býður og hvers konar upplifun fylgir.",
			FeatureItems: []genFeature{
				{Title: "Andlitsmyndatökur", Body: "Náttúrulegar og afslappaðar myndatökur fyrir þau sem vilja einlægar myndir án stífra fyrirmæla."},
				{Title: "Myndir fyrir vörumerki", Body: "Snyrtilegt safn af myndum fyrir vefsíður, herferðir, kynningar og daglega markaðssetningu."},
				{Title: "Viðburðir og tilefni", Body: "Myndataka sem heldur deginum gangandi en nær samt augnablikunum sem fólk man eftir."},
			},
			AboutHeading:    "Rólegt ferli skilar betri myndum",
			AboutBody:       "Notaðu þetta pláss til að lýsa myndstílnum þínum, hvernig myndataka er í raun og af hverju fólk fer heim með myndir sem líkjast því sjálfu.",
			GalleryHeading:  "Nýlegar myndatökur",
			GalleryBody:     "Skiptu verkunum í nokkur afmörkuð dæmi: andlitsmyndir, viðburði eða vörumerkjamyndir sem sýna fjölbreytni án þess að yfirfylla síðuna.",
			SiteGoal:        "Breyta gestum í fyrirspurnir og bókaðar myndatökur.",
			HomeHeadline:    "Náttúrulegar ljósmyndir af raunverulegu fólki, stöðum og augnablikum",
			HomeSubheadline: "Notaðu þessi drög til að kynna stílinn þinn, sýna verkin og gera bókun einfalda.",
			AboutIntro:      "Byrjaðu á þeim augnablikum sem þú hjálpar fólki að varðveita og lýstu svo afslöppuðu andrúmsloftinu við myndatökuna.",
			WorkProcess:     "Gott ferli fer yfirleitt frá stuttri fyrirspurn í skýra skipulagningu, afslappaða myndatöku og snyrtilega afhendingu fullunninna mynda.",
			FooterTagline:   "Róleg skipulagning, einlægar myndir og einföld leið að bókun.",
		},
		"florist": {
			CategoryLabel: "Blómastofa",
			PrimaryCTA:    "Spurðu um pöntun",
			ServicesTitle: "Blómaverk eftir árstíðum",
			ServicesIntro: "Dragðu fram það sem skiptir mestu: brúðkaup, vikuleg blóm, sérpantanir og stakar uppsetningar.",
			FeatureItems: []genFeature{
				{Title: "Blóm fyrir viðburði", Body: "Hönnun fyrir matarboð, opnanir, hátíðir og brúðkaup sem kalla á hlýju frekar en prjál."},
				{Title: "Vikuleg blóm", Body: "Regluleg blóm fyrir verslanir, stofur, skrifstofur eða heimili sem vilja notalegt rými."},
				{Title: "Sérpantanir", Body: "Minni pantanir, gjafavendir og sérstakar óskir afgreiddar í skýru ferli."},
			},
			SiteGoal:        "Breyta gestum í blómapantanir, fyrirspurnir um viðburði og fasta viðskiptavini.",
			HomeHeadline:    "Blóm fyrir samverustundir, gjafir og hversdagsborðið",
			HomeSubheadline: "Byrjaðu á hlýlegu yfirliti yfir árstíðabundin verk, sérpantanir og viðburðina eða rýmin sem þú mótar.",
			AboutIntro:      "Byggðu síðuna á árstíðum, stemningu og þeim pöntunum sem þú vilt raunverulega fá.",
			WorkProcess:     "Haltu ferlinu einföldu: stutt fyrirspurn, snögg samræming um umfang og stemningu og svo skýr leið að afhendingu eða uppsetningu.",
		},
		"wellness": {
			CategoryLabel: "Heilsustofa",
			PrimaryCTA:    "Bókaðu tíma",
			ServicesTitle: "Tímar og stuðningur",
			ServicesIntro: "Einbeittu þér að fáum leiðum til að vinna með þér svo leiðin frá forvitni að bókun sé stutt.",
			FeatureItems: []genFeature{
				{Title: "Einkatímar", Body: "Einstaklingsstuðningur sniðinn að manneskju, markmiði eða tímabili í lífinu."},
				{Title: "Hóptímar", Body: "Námskeið, hringir eða litlir hópar sem skapa takt án þess að missa hlýjuna."},
				{Title: "Hagnýt leiðsögn", Body: "Jarðbundin útskýring á því hvað gerist, hverjum það hjálpar og hvernig þú veist hvort það hentar þér."},
			},
			SiteGoal:        "Breyta gestum í bókaða tíma og örugg fyrstu samtöl.",
			HomeHeadline:    "Stöðugri iðja fyrir þreyttan líkama og háværan huga",
			HomeSubheadline: "Gefðu nýjum gestum rólega útskýringu á því sem þú býður, hverjum það hjálpar og einföldustu leiðinni til að byrja.",
			AboutIntro:      "Útskýrðu nálgun þína á einföldu máli: hvað gerist, hvernig það er og hverju má búast við eftir fyrsta tímann.",
			WorkProcess:     "Hér snýst allt um skýrleika: fyrir hverja þetta er, hvernig stuðningurinn lítur út í raun og hvenær fólk á að hafa samband.",
			FooterTagline:   "Jarðbundinn stuðningur, einfalt mál og mildara fyrsta skref.",
		},
		"creative": {
			CategoryLabel: "Hönnunarstofa",
			PrimaryCTA:    "Byrjaðu verkefni",
			ServicesTitle: "Þjónusta og áskriftir",
			ServicesIntro: "Byggðu tilboðið á fáum útkomum frekar en löngum lista af verkum.",
			FeatureItems: []genFeature{
				{Title: "Vörumerkjakerfi", Body: "Vörumerkjavinna sem gefur litlum fyrirtækjum skýrari mynd, rödd og sjónrænan takt."},
				{Title: "Kynningarsíður", Body: "Markvissar síður fyrir tilboð, opnanir eða herferðir sem þurfa að komast út án tafar."},
				{Title: "Áframhaldandi stuðningur", Body: "Sveigjanleg leið til að halda texta, hönnun og vefuppfærslum gangandi eftir fyrstu opnun."},
			},
			SiteGoal:        "Breyta gestum í vandaðar verkefnafyrirspurnir.",
			HomeHeadline:    "Vönduð hönnun fyrir lítil fyrirtæki sem þurfa að líta vel út",
			HomeSubheadline: "Settu tilboðið fram út frá útkomum, ekki fagmáli, svo réttu viðskiptavinirnir skilji virðið strax.",
			AboutIntro:      "Lýstu því hvernig þú vinnur með litlum teymum svo ferlið virki skipulagt án þess að hljóma stíft eða uppblásið.",
			WorkProcess:     "Góð verkefni byrja á umfangi, stefnu og skýru boðvaldi og fara svo í gegnum hnitmiðaðar umferðir í stað endalauss reks.",
		},
		"craft": {
			CategoryLabel: "Handverksstofa",
			PrimaryCTA:    "Sjáðu næstu vinnustofur",
			ServicesTitle: "Verk, sérpantanir og vinnustofur",
			ServicesIntro: "Útskýrðu hvað er fáanlegt núna, hvað er hægt að sérpanta og hvernig námskeið eða vinnustofur passa inn.",
			FeatureItems: []genFeature{
				{Title: "Verk í litlu upplagi", Body: "Takmörkuð upplög og árstíðabundin verk með nægri sögu til að hvert stykki verði áþreifanlegt."},
				{Title: "Sérsmíði", Body: "Leiðir fyrir viðskiptavini sem vilja fá eitthvað smíðað fyrir rými, viðburð eða gjöf."},
				{Title: "Verklegar vinnustofur", Body: "Stutt námskeið þar sem fólk lærir efnið, ferlið og taktinn á bak við verkin."},
			},
			SiteGoal:        "Breyta gestum í bókaðar vinnustofur, sérpantanir og áhuga á vörum.",
			HomeHeadline:    "Handverk með raunverulegri áferð, hagnýtri fegurð og rými til að læra",
			HomeSubheadline: "Útskýrðu blönduna af vörum, sérpöntunum og vinnustofum á einum stað án þess að missa handverkstilfinninguna.",
			AboutIntro:      "Notaðu síðuna til að tengja fullkláruð verk við efnið, aðferðirnar og kennsluna á bak við þau.",
			WorkProcess:     "Fólk kann að meta að sjá handverkið og skilja taktinn á bak við það, hvort sem það endar í námskeiði, sérpöntun eða kaupum.",
			FooterTagline:   "Handverk, hagnýt fegurð og rými til að læra með því að gera.",
		},
		"food": {
			CategoryLabel: "Matarstaður í hverfinu",
			PrimaryCTA:    "Skipuleggðu heimsókn",
			ServicesTitle: "Það helsta á matseðlinum og pantanir",
			ServicesIntro: "Haltu þessu hagnýtu: hvað er í boði, hvenær er opið og hvernig má panta fyrir stærri tilefni.",
			FeatureItems: []genFeature{
				{Title: "Dagsins réttir", Body: "Breytilegt úrval af fersku sem heldur föstum gestum forvitnum og hjálpar nýjum að rata."},
				{Title: "Forpantanir", Body: "Skýr leið til að panta kökur, kassa eða stærri pantanir án mikilla samskipta fram og til baka."},
				{Title: "Viðburðir og veitingar", Body: "Einfalt yfirlit yfir hvers konar tilefni þú sinnir og hvernig má spyrjast fyrir."},
			},
			SiteGoal:        "Breyta gestum í heimsóknir, forpantanir og fyrirspurnir um veitingar.",
			HomeHeadline:    "Staður í hverfinu sem fólk vill koma aftur á",
			HomeSubheadline: "Sýndu andrúmsloftið, það sem er í boði og næsta skref áður en gesturinn fer að leita að hagnýtum upplýsingum annars staðar.",
			AboutIntro:      "Góð matarsíða gefur nóg af stemningu til að heimsókn hljómi vel án þess að grunnupplýsingar verði að feluleik.",
			WorkProcess:     "Matarstöðum hentar að útskýra einfaldlega hvað er ferskt, hvað breytist oft og hvernig stærri eða sérstakar pantanir eru afgreiddar.",
		},
	},
	Pricing: map[string][]genPricingPlan{
		"photography": {
			{
				Name:        "Andlitsmyndataka",
				Price:       "Frá 45.000 kr.",
				Description: "Afmörkuð myndataka fyrir einstaklinga, pör eða fjölskyldur sem vilja afslappaða leiðsögn og snyrtilegt myndasafn.",
				Features:    []string{"Undirbúningssímtal", "Unnið myndasafn", "Einkasafn"},
				CTALabel:    "Spurðu um myndatökur",
			},
			{
				Name:        "Myndir fyrir vörumerki",
				Price:       "Frá 90.000 kr.",
				Description: "Hálfs- eða heilsdagspakki fyrir opnanir, herferðir eða myndir á vefsíðu lítilla fyrirtækja.",
				Features:    []string{"Aðstoð við myndalista", "Tilbúnar myndir til notkunar", "Afhendingaráætlun"},
				CTALabel:    "Skipuleggðu myndatökuna",
			},
		},
		"wellness": {
			{
				Name:        "Einkatímar",
				Price:       "Frá 12.000 kr.",
				Description: "Einstaklingsvinna fyrir þau sem vilja sérsniðinn stuðning og rólegri byrjun.",
				Features:    []string{"Eigin hraði", "Hagnýt leiðsögn", "Punktar í kjölfarið"},
				CTALabel:    "Spurðu um tíma",
			},
			{
				Name:        "Námskeið í litlum hópi",
				Price:       "Frá 28.000 kr.",
				Description: "Stutt námskeið fyrir þau sem vilja samfellu, umgjörð og sameiginlegan takt.",
				Features:    []string{"Hópaform", "Endurteknir tímar", "Skýr næstu skref"},
				CTALabel:    "Spurðu um dagsetningar",
			},
		},
		categoryBusiness: {
			{
				Name:        "Grunnpakki",
				Price:       "Frá 35.000 kr.",
				Description: "Minni pakki fyrir afmarkaða vinnu þar sem markmið og umfang eru þegar nokkuð skýr.",
				Features:    []string{"Skilgreint umfang", "Skýr tímarammi", "Einföld afhending"},
				CTALabel:    "Spurðu hvort þetta henti",
			},
			{
				Name:        "Heildarpakki",
				Price:       "Frá 90.000 kr.",
				Description: "Stærri pakki fyrir verkefni sem þurfa meira samstarf, mótun eða umfang.",
				Features:    []string{"Sameiginleg skipulagning", "Meira umfang", "Vönduð afhending"},
				CTALabel:    "Byrjum samtalið",
			},
		},
	},
	Testimonials: map[string][]genTestimonial{
		"photography": {
			{Quote: "Allt ferlið var rólegt og skýrt og myndirnar litu enn út eins og við sjálf, ekki einhver uppstillt útgáfa af okkur.", Name: "Mira L.", Role: "Andlitsmyndaviðskiptavinur"},
			{Quote: "Við fengum myndir sem gerðu vefsíðuna loksins nútímalega, samræmda og tilbúna til að vísa fólki á.", Name: "Aren Studio", Role: "Vörumerkjaviðskiptavinur"},
		},
		"wellness": {
			{Quote: "Tímarnir voru jarðbundnir frá fyrstu mínútu og ég fór út og vissi nákvæmlega hverju ég vildi halda áfram með.", Name: "Elín S.", Role: "Einkaviðskiptavinur"},
			{Quote: "Allt var útskýrt á einföldu máli, sem gerði það mun auðveldara að bóka en annars staðar sem ég skoðaði.", Name: "Jóhann K.", Role: "Nýr viðskiptavinur"},
		},
		categoryBusiness: {
			{Quote: "Þetta var óvænt einfalt og útkoman leit út fyrir að vera vandaðri en ég bjóst við svona snemma.", Name: "Nóra P.", Role: "Viðskiptavinur"},
			{Quote: "Skýr samskipti, ekkert vesen og lokaútkoma sem passaði nákvæmlega við það hvernig við vildum að fyrirtækið kæmi fyrir.", Name: "S. Berg", Role: "Eigandi"},
		},
	},
	FAQ: map[string][]genFAQ{
		"photography": {
			{Question: "Hversu miklar upplýsingar á ég að senda í fyrsta tölvupósti?", Answer: "Stutt lýsing á tegund myndatöku, gróflega tímasetningu og til hvers myndirnar eiga að nýtast er nóg til að byrja."},
			{Question: "Þarf ég að vera með fullmótaða hugmynd áður en ég hef samband?", Answer: "Nei. Gróf hugmynd dugar og við mótum smáatriðin saman þegar samtalið byrjar."},
		},
		"wellness": {
			{Question: "Hvernig veit ég hvort þetta hentar mér?", Answer: "Notaðu fyrsta samtalið til að spyrja hagnýtra spurninga um hraða, form og hvernig stuðningurinn er yfirleitt."},
			{Question: "Hvað á ég að taka með í fyrsta tímann?", Answer: "Það dugar yfirleitt að hafa hugmynd um hvað er erfitt núna og hvers konar stuðning þú vonast eftir."},
		},
		categoryBusiness: {
			{Question: "Hvað er gott að hafa með í fyrstu fyrirspurn?", Answer: "Smá samhengi um tímasetningu, umfang og hvers konar aðstoð þú þarft er nóg til að koma góðu samtali af stað."},
			{Question: "Tekurðu líka að þér minni verkefni?", Answer: "Notaðu þetta svar til að útskýra hvort það sé lágmarksumfang, grunnpakki eða ábending annað þegar verkefni er of lítið."},
		},
	},
	Team: map[string][]genTeamMember{
		"creative": {
			{Name: "Hönnunarstjóri", Role: "Stefna og umgjörð", Bio: "Mótar verkefnið, heldur vinnunni markvissri og passar að lokaútkoman hljómi enn eins og fyrirtækið.", Links: []genLink{{Label: "Byrjaðu verkefni", Href: "/contact"}}},
			{Name: "Verkefnastjóri", Role: "Skipulag og afhending", Bio: "Sér um tímasetningar, yfirferðir og hagnýtu smáatriðin sem koma í veg fyrir að lítið verkefni verði langt.", Links: []genLink{{Label: "Spurðu spurningar", Href: "/contact"}}},
		},
		categoryBusiness: {
			{Name: "Stofnandi", Role: "Aðaltengiliður", Bio: "Ber ábyrgð á vinnunni, heldur samskiptum beinum og fylgist með smáatriðunum sem móta lokaupplifunina.", Links: []genLink{{Label: "Hafðu samband", Href: "/contact"}}},
		},
	},
	UI: map[string]string{
		"nav.home":      "Heim",
		"nav.services":  "Þjónusta",
		"nav.workshops": "Vinnustofur",
		"nav.gallery":   "Myndir",
		"nav.about":     "Um okkur",
		"nav.contact":   "Hafðu samband",

		"home.textHeading":  "Fyrstu drög mótuð utan um raunverulega vinnu",
		"home.imageHeading": "Hvernig vinnan er yfirleitt",

		"services.featuresHeading": "Hvað fylgir",
		"services.featuresIntro":   "Notaðu þessi spjöld til að lýsa dæmigerðum leiðum, afurðum eða því hvernig hægt er að vinna með þér.",
		"services.ctaHeading":      "Þarftu útgáfu sem er sniðin að þínu verkefni?",
		"services.ctaBody":         "Bjóddu fólki að spyrja um tímasetningu, umfang eða hvort þetta henti í stað þess að láta það giska á hvernig á að byrja.",

		"workshops.item1.title":     "Kynningartímar",
		"workshops.item1.body":      "Afslappað fyrsta skref fyrir þau sem vilja prófa formið áður en þau skuldbinda sig frekar.",
		"workshops.item2.title":     "Vinnustofur í litlum hópi",
		"workshops.item2.body":      "Markvissar stundir með nægri umgjörð til að kenna gagnlega færni og nægu rými til að halda þeim persónulegum.",
		"workshops.item3.title":     "Einkabókanir",
		"workshops.item3.body":      "Sérsniðnar stundir fyrir teymi, viðburði eða fólk sem þarf sérstakara form.",
		"workshops.textHeading":     "Lærðu með því að gera",
		"workshops.textBody":        "Lýstu hraðanum, efninu og hversu mikil leiðsögn fylgir svo fólk sjái fljótt hvort námskeiðið henti því.",
		"workshops.featuresHeading": "Leiðir til að taka þátt",
		"workshops.featuresIntro":   "Notaðu þessi spjöld sem upphafsvalmynd fyrir kennsluformin þín.",
		"workshops.ctaHeading":      "Vantar þig næstu dagsetningu eða einkabókun?",
		"workshops.ctaBody":         "Bjóddu upp á samtal áður en þú byggir flóknara skráningarferli.",
		"workshops.ctaLabel":        "Spurðu um vinnustofur",
		"workshops.seoDescription":  "Námskeið, hóptímar og einkabókanir.",

		"about.imageHeading": "Af hverju fólk kemur aftur",
		"about.ctaHeading":   "Ef nálgunin hentar á næsta skref að vera einfalt",
		"about.ctaBody":      "Notaðu lok síðunnar til að bjóða heimsókn, spurningu eða bókun án þess að breyta um tón.",

		"gallery.galleryHeading": "Lítið úrval af einkennandi verkum",
		"gallery.galleryIntro":   "Þessi hólf geta geymt verkmyndir, dæmi frá viðburðum eða vörumyndir án þess að þurfa stærra myndakerfi strax.",
		"gallery.image1.title":   "Einkennandi verk",
		"gallery.image1.caption": "Notaðu fyrsta hólfið fyrir verkið sem fangar best tón fyrirtækisins.",
		"gallery.image2.title":   "Smáatriði úr ferlinu",
		"gallery.image2.caption": "Bættu við nærmynd sem sýnir áferð, efni eða hvernig verkið er unnið.",
		"gallery.image3.title":   "Fullkláruð útkoma",
		"gallery.image3.caption": "Notaðu síðasta hólfið til að sýna útkomuna í samhengi svo gestir sjái raunverulega notkun fyrir sér.",
		"gallery.ctaHeading":     "Búinn að sjá nóg til að spyrja um þitt eigið verkefni?",
		"gallery.ctaBody":        "Þessi síða á að enda á skýrasta næsta skrefi, ekki á blindgötu.",

		"contact.eyebrow":         "Hafðu samband",
		"contact.heroCtaLabel":    "Sendu fyrirspurn",
		"contact.textHeading":     "Hvað er gott að hafa með þegar þú hefur samband",
		"contact.textBody":        "Stutt lýsing á tímasetningu, kostnaði, umfangi eða hvers konar aðstoð þú þarft er nóg til að hefja gott samtal.",
		"contact.formHeading":     "Sendu stutta fyrirspurn",
		"contact.formIntro":       "Notaðu formið fyrir tímasetningu, laus pláss, séróskir eða fyrstu spurninguna sem kemur verkefninu af stað.",
		"contact.formSubmitLabel": "Senda fyrirspurn",
		"contact.field.name":      "Nafn",
		"contact.field.email":     "Netfang",
		"contact.field.phone":     "Sími",
		"contact.field.message":   "Skilaboð",
		"contact.ctaHeading":      "Viltu frekar senda tölvupóst?",
		"contact.ctaBody":         "Hafðu beint netfang sýnilegt fyrir þau sem vilja frekar skrifa úr eigin pósthólfi.",
		"contact.ctaLabel":        "Sendu póst á hello@example.com",

		"testimonials.heading":   "Það sem viðskiptavinir taka yfirleitt eftir",
		"testimonials.intro":     "Hafðu tilvitnanirnar stuttar, áþreifanlegar og tengdar raunverulegri reynslu af samstarfinu.",
		"pricing.heading":        "Pakkar og byrjunarpunktar",
		"pricing.intro":          "Notaðu þetta sem skýra byrjunarpunkta svo gestir átti sig á umfangi áður en þeir hafa samband.",
		"faq.heading":            "Spurningar sem fólk spyr áður en það hefur samband",
		"faq.intro":              "Notaðu þetta pláss til að minnka fyrirstöðu, setja væntingar og gera næsta skref einfalt.",
		"team.heading":           "Fólkið á bak við verkin",
		"team.intro":             "Lítill teymiskafli virkar best þegar hann útskýrir hvað hver og einn leggur raunverulega til upplifunar viðskiptavina.",
		"footer.copyrightPrefix": "Höfundarréttur 2026 ",

		"assumptions.contact":   "Tenglar fyrir samskipti nota gervinetfang þar til form eða raunverulegar samskiptaupplýsingar bætast við.",
		"assumptions.gallery":   "Myndakaflar nota gervimyndahólf þar til hægt er að hlaða inn myndum.",
		"assumptions.workshops": "Upplýsingar um vinnustofur og námskeið eru settar fram sem markaðsefni, ekki bókunarkerfi.",
	},
}
